global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "rpi_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["rpi-exporter:9110"]
